### PR TITLE
Use unit structs for parsers

### LINKED ISSUE #347: Unhelpful `phylum analyze` output for nonexistent lock file
# Overview
A small typo in the filename for the lockfile is an easy mistake to make. But the error message output by `phylum analyze` is very unhelpful and says nothing about the file being nonexistent.

```
❯ phylum analyze reqiurements.txt
[2022-05-04T21:04:44Z WARN  phylum_cli::commands::lock_files] Attempting to obtain packages from unrecognized lockfile type: reqiurements.txt
[2022-05-04T21:04:44Z ERROR phylum] Execution failed: Unable to locate any valid package in package lockfile
❗ Error: Execution failed caused by: Unable to locate any valid package in package lockfile
```

# Expected Behavior
An error message that says something like "file not found"

# Additional Context
I'm asking for a freind of course... I have no truoble at all with my spelling 😅

### PR DESCRIPTION
**Pull request by kylewillmon**
This changes our parsers to be strategy objects so that they are a bit
easier to use. This allows us to simplify the LOCKFILE_PARSERS array in
commands/parser.rs and use that array in try_get_packages instead of a
macro.

Closes #347

As @cd-work suggested in #398:

> Maybe having the parsers completely stateless, just taking a &str as parameter would be the way to go.

This patch takes that idea and runs with it.

### CODE REVIEW

File: cli/src/lockfiles/mod.rs [hunk 1]
```diff
@@ -20,12 +19,15 @@ pub use ruby::GemLock;
...
-    fn new(filename: &Path) -> Result<Self, io::Error>
-    where
-        Self: Sized;
-
-    fn parse(&self) -> ParseResult;
+pub trait Parse {
+    /// Parse from a string
+    fn parse(&self, data: &str) -> ParseResult;
+    /// Indicate the type of packages parsed by this parser
+    fn package_type(&self) -> PackageType;
```
Comment (mathew-horner) [inline cli/src/lockfiles/mod.rs:26]: Could this still just be a static function? Not a big deal either way, but I think it makes more sense semantically to not have the reference to self. This function only cares about the implementing type, not the instance.

**Review by mathew-horner — DISMISSED** [review]
Look good 👍

File: cli/src/lockfiles/mod.rs [hunk 2]
```diff
@@ -20,12 +19,15 @@ pub use ruby::GemLock;
...
+}
 
-    fn package_type() -> PackageType;
+/// Parse a file with the given parser.
+pub fn parse_file<T: Parse, P: AsRef<Path>>(parser: T, path: P) -> ParseResult {
+    let data = read_to_string(path)?;
+    parser.parse(&data)
 }
```
Comment (cd-work) [inline cli/src/lockfiles/mod.rs:33]: This might as well be a method on the trait, right? Like one that is already implemented by default.

**Review by cd-work — APPROVED** [review]
Approving so I don't block merge, but I'd suggest considering my suggestion before merge.

File: cli/src/lockfiles/mod.rs (hunk 1 above)
Comment (kylewillmon) [reply cli/src/lockfiles/mod.rs:26]: Non-methods cannot be dispatched from trait objects (see [object safety](https://doc.rust-lang.org/reference/items/traits.html#object-safety)). So if this was a static function and we have something of type `&dyn Parse`, we would have no way to call this function.

Comment (mathew-horner) [reply cli/src/lockfiles/mod.rs:26]: Right, my mistake

File: cli/src/lockfiles/mod.rs (hunk 2 above)
Comment (kylewillmon) [reply cli/src/lockfiles/mod.rs:33]: Yep. I think that makes sense

**Review by mathew-horner — APPROVED** [review]
