### PR TITLE
Transitioning away from `musl`

### LINKED ISSUE #426: Cannot use deno on x86_64-unknown-linux-musl
As seen in [this CI build](https://github.com/phylum-dev/cli/runs/6579718604?check_suite_focus=true), building deno fails for `x86_64-unknown-linux-musl` targets. This is because [rusty_v8](https://github.com/denoland/rusty_v8) does not support this target (see denoland/rusty_v8#49).

### PR DESCRIPTION
**Pull request by andreaphylum**
This PR changes the installation scripts and the `README` to refer to the new `gnu` based binaries.

Opening as draft PR to request feedback on wording and alternative strategies.

Closes #426.

### CODE REVIEW

File: cli/src/install.sh [hunk 1]
```diff
@@ -95,6 +95,17 @@ source ${completions_dir}/phylum.bash" \
     success "Completions are enabled for bash."
 }
 
+check_glibc() {
+    # On systems with musl libc, running ldd on phylum will exit with an error.
+    # If that happens, report an explanation and exit.
+    ldd phylum >/dev/null 2>&1
+    if [ $? != 0 ]; then
```
Comment (kylewillmon) [inline cli/src/install.sh:102]: It's much more natural to put the call directly in the if

```suggestion
    if ldd phylum >/dev/null 2>&1; then
```

File: cli/src/install.sh [hunk 2]
```diff
@@ -141,6 +152,7 @@ cleanup_pre_xdg() {
 
 cd "$(dirname "$0")"
 banner
+check_glibc
```
Comment (kylewillmon) [inline cli/src/install.sh:155]: We only rely on `glibc` on Linux. We need to guard this so that it doesn't run on macos installs.

File: README.md [hunk 3]
```diff
@@ -80,6 +80,16 @@ extensions:
...
+### musl support
+
+Following the release of the extensions feature, as of version 3.8.0, Phylum CLI
+has a dependency on `glibc` and thus can no longer support `musl` compilation targets.
+
+This means that `phylum` won't be executable in environments such as Alpine Linux.
+
+If your use case requires a lightweight Docker base image, consider using
+[Debian slim](https://hub.docker.com/_/debian).
+
```
Comment (kylewillmon) [inline README.md:92]: I don't like the idea of saying that we "can no longer support" musl. Users can still build from source to get binaries that are dynamically-linked against musl. And some truly advanced user may even find a way to build a statically-linked version.

The change is the binaries that we provide. Here's a possible way to write this section:

```suggestion
### libc version

As of version 3.8.0, the provided Linux binaries of the Phylum CLI depend on
`glibc`. We no longer provide binaries that are statically compiled with `musl`
libc

This means the provided binaries won't be executable in environments such as
Alpine Linux.

If your use case requires a lightweight Docker base image, consider using
[Debian slim](https://hub.docker.com/_/debian) or [building from
source](https://docs.phylum.io/docs/alternate_install)
```

**Review by kylewillmon — CHANGES_REQUESTED** [review]

File: README.md [hunk 4]
```diff
@@ -80,6 +80,21 @@ extensions:
 
 https://github.com/phylum-dev/cli/tree/main/extensions
 
+### musl support
```
Comment (kylewillmon) [inline README.md:83]: I still think the heading here could be improved. This section isn't really talking about `musl support` because we can still build against musl libc as long as we dynamically link.

I think a heading like `libc version` or `libc requirement` would be more accurate.

**Review by kylewillmon — APPROVED** [review]
There are still other things to do. Specifically:

1. Update the release workflow to create the `*-gnu.zip` files
2. Update the code for `phylum update` to use `-gnu` instead of `-musl`

It should be simple enough to add the second item to this PR. The first item can be left for its own PR.

File: cli/src/install.sh [hunk 5]
```diff
@@ -95,6 +95,24 @@ source ${completions_dir}/phylum.bash" \
...
+    if [ "${platform_str}" != "Linux" ]; then
+        return 0
+    fi
+
+    # On systems with musl libc, running ldd on phylum will exit with an error.
+    # If that happens, report an explanation and exit.
+    if ! ldd phylum >/dev/null 2>&1; then
+        error "The current operating system does not support running Phylum. Please use a system with glibc."
+        error "See: https://github.com/phylum-dev/cli#musl-support"
+        echo
```
[the remark this answers is not in the document]
Comment (cd-work) [reply cli/src/install.sh:111]: Empty line I'd assume?

**Review by kylewillmon — APPROVED** [review]

**Review by kylewillmon — APPROVED** [review]

File: README.md [hunk 6]
```diff
@@ -80,6 +80,18 @@ extensions:
...
 
+### musl binaries
+
+As of version 3.8.0, the provided Linux binaries of the Phylum CLI depend on
+`glibc`. We no longer provide binaries that are statically compiled with the
+`musl` libc.
+
+This means the provided binaries won't be executable in environments such as
+Alpine Linux. If your use case requires a lightweight Docker base image,
+consider using [Debian slim](debian-slim) instead.
```
Comment (maxrake) [inline README.md:91]:
```suggestion
consider using [Debian slim][debian-slim] instead.
```
This is a broken link otherwise.

**Review by maxrake — COMMENTED** [review]
The `Trigger` job in the `release` workflow can also be uncommented here...even though that trigger won't be approved for the v3.8.0 release.
