### PR TITLE
Fix help output sort order

### LINKED ISSUE #727: Subcommands are in random order
After the latest clap update, our subcommands are listed in random order in our help output. They should be in alphabetical order for easy searching.

```
❯ phylum help
Client interface to the Phylum system

Usage: phylum [OPTIONS] <COMMAND>

Commands:
  update     Check for a new release of the Phylum CLI tool and update if one exists
  history    Return information about historical jobs
  project    Create, list, link and set thresholds for projects
  package    Retrieve the details of a specific package
  auth       Manage authentication, registration, and API keys
  ping       Ping the remote system to verify it is available
  parse      Parse a lockfile
  analyze    Submit a request for analysis to the processing system
  version    Display application version
  group      Interact with user groups
  extension  Manage extensions
  yarn       
  poetry     
  npm        
  uninstall  Uninstall the Phylum CLI
  help       Print this message or the help of the given subcommand(s)

Options:
  -c, --config <FILE>         Sets a custom config file
  -t, --timeout <TIMEOUT>     Set the timeout (in seconds) for requests to the Phylum api
      --no-check-certificate  Don't validate the server certificate when performing api requests
  -h, --help                  Print help information
  -V, --version               Print version information
```

### PR DESCRIPTION
**Pull request by cd-work**
This fixes a regression introduced in the clap 4 update (925de7d) which caused the help output to be sorted in order of definition rather than alphabetically.

Fixes #727.

### CODE REVIEW

File: cli/src/app.rs [hunk 1]
```diff
@@ -31,6 +31,7 @@ pub fn app() -> Command {
         .version(VERSION)
         .author("Phylum, Inc.")
         .about("Client interface to the Phylum system")
+        .next_display_order(None)
```
Comment (kylewillmon) [inline cli/src/app.rs:34]: I've read the docs for this function and I still have no idea how you figured this out...

Comment (cd-work) [reply cli/src/app.rs:34]: By looking at the changelog. ;)

https://github.com/clap-rs/clap/blob/master/CHANGELOG.md

**Review by kylewillmon — APPROVED** [review]

**Review by kylewillmon — APPROVED** [review]
