### PR TITLE
lockfile paths

### LINKED ISSUE #973: project files in parent directories not found
# Overview
The `phylum_project` crate has a function `get_current_project` which is used for locating the `.phylum_project` file. It's supposed to find the file if it is in the current directory or a parent directory (up to 32 levels up).

However, it starts with a path of `"."` and then navigates upwards by removing path components. Parent directories are never searched because successively removing the last components of `"."` yields only `""`.

# How To Reproduce
Steps to reproduce this behavior:
1. Go to the docs folder in this repository.
2. Run `phylum parse`
3. Get `❗ Error: Missing lockfile parameter`.

# Expected Behavior
The project file in the root of the project should be found and the lockfiles should be parsed.

### PR DESCRIPTION
**Pull request by matt-phylum**
This PR fixes a couple issues I noticed while looking at the `phylum_project` crate.

1. `ProjectConfig::lockfiles()` returns different paths before and after the first serialization. This shouldn't be a problem for CLI because I doubt the configuration is ever used this way without first being serialized and whether or not the path starts with an extra `"./"` is not normally a problem when operating on real filesystems, so I doubt it's causing any problems today. I removed the extra `"./"`.
2. `get_current_project()` calls `find_project_conf(".", true)` and then `find_project_conf` uses `Path::parent()` to navigate to parent directories. `Path::parent()` gets the parent path, not the parent directory, because it operates only on the textual representation of the path without hitting the filesystem. The parent of `"."` is not `".."` so whether you pass `true` or not for the second parameter to `find_project_conf` doesn't matter. I changed `get_current_project()` to canonicalize paths. Alternatively, we could convert to an absolute path, but the behavior would be different wrt symlinks etc (eg the test I've written would not work).

Closes #973

## Checklist

- [x] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?
- [x] Have you ensured that you have met the expected acceptance criteria?
- [x] Have you created sufficient tests?
- [x] Have you updated all affected documentation?

### CODE REVIEW

**Review by maxrake — APPROVED** [review]
Confirmed with local testing. The code changes appear fine to my non-rusty eye. The added tests are very welcome! Not sure how we missed this when adding the feature.
LGTM.

File: phylum_project/src/lib.rs [hunk 1]
```diff
@@ -93,7 +93,10 @@ pub fn find_project_conf(
     recurse_upwards: bool,
 ) -> Option<PathBuf> {
     let max_depth = if recurse_upwards { 32 } else { 1 };
-    let mut path = starting_directory.as_ref();
+    let path = starting_directory.as_ref();
+    // If `path` is like `.`, `path.parent()` is `None`.
+    let canonicalized = path.canonicalize();
+    let mut path = canonicalized.as_deref().ok().unwrap_or(path);
```
Comment (cd-work) [inline phylum_project/src/lib.rs:99]: I don't think there's any point to `unwrap_or` here? Seems like this would be much easier by just doing `canonicalize().ok()?`.

**Review by cd-work — CHANGES_REQUESTED** [review]

File: phylum_project/src/lib.rs (hunk 1 above)
Comment (matt-phylum) [reply phylum_project/src/lib.rs:99]: `.ok()?` would cause the function to fail if the path does not exist, which the old code did not do.

**Review by maxrake — DISMISSED** [review]
Tested again...still works. LGTM.

File: phylum_project/src/lib.rs [hunk 2]
```diff
@@ -93,15 +93,23 @@ pub fn find_project_conf(
...
+    let mut path = starting_directory.as_ref().canonicalize().ok()?;
 
     for _ in 0..max_depth {
-        let conf_path = path.join(PROJ_CONF_FILE);
-        if conf_path.is_file() {
-            return Some(conf_path);
+        path.push(PROJ_CONF_FILE);
+        if path.is_file() {
+            return Some(path);
         }
```
Comment (cd-work) [inline phylum_project/src/lib.rs:105]: Why was this logic changed from join to push?

**Review by cd-work — CHANGES_REQUESTED** [review]

**Review by cd-work — APPROVED** [review]

**Review by maxrake — APPROVED** [review]
Tested again...still works. LGTM.
