### PR TITLE
fix: `pip` parser fails for some lines containing comments

### LINKED ISSUE #1044: `requirements.txt` parser fails on valid files
# Overview
Some build systems generate `requirements.txt` files with comments on adjacent lines. 

`phylum analyze` and `phylum parse` fail to parse these files. 

# How To Reproduce
1. Using https://github.com/hypothesis/h/blob/main/requirements/requirements.txt as input, run `phylum analyze` 
2. Observe error (tested on Version v5.0.1-1-g0612262)
```
PS C:\projects\FirstBlood\REPOS\hypothesis\h\requirements> phylum analyze .\requirements.txt
❗ Error: Unable to locate any valid package in lockfile ".\\requirements.txt"

Caused by:
    0: Failed to parse lockfile ".\\requirements.txt"
    1: Failed to parse requirements file
    2: 0: at line 8, in AlphaNumeric:
           # via -r requirements/requirements.in
```

# Expected Behavior
`requirements.txt` files with comments should not fail parsing

### PR DESCRIPTION
**Pull request by maxrake**
The `pip` "Requirements File Format" is documented here: https://pip.pypa.io/en/stable/reference/requirements-file-format/

It allows for line continuations and a host of arguments to `pip install`, which this change does not address. Instead, this change accounts for lines containing comments where the comment character (`#`) is not the first character of the line. The comment line could be indented or comments can be inline (e.g., after a valid requirement). Both types of comments were added to the test fixture.

When updating the `CHANGELOG.md`, saving the file in the IDE caused an automatic reformatting of some lines...to remove trailing whitespace and ensure consistency for the list markers (`-` everywhere instead of `*`).

Fixes #1044

## Checklist

- [x] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?
- [x] Have you ensured that you have met the expected acceptance criteria?
- [x] Have you created sufficient tests?
- [x] Have you updated all affected documentation?
- [x] Have you updated CHANGELOG.md (or extensions/CHANGELOG.md), if applicable

### CODE REVIEW

File: lockfile/src/parsers/pypi.rs [hunk 1]
```diff
@@ -17,7 +17,10 @@ pub fn parse(input: &str) -> Result<&str, Vec<Package>> {
     let mut pkgs = Vec::new();
 
     // Iterate over all non-empty lines.
-    for line in input.lines().filter(|line| !line.starts_with('#') && !line.trim().is_empty()) {
+    for line in
+        input.lines().filter(|line| !line.trim().starts_with('#') && !line.trim().is_empty())
```
Comment (cd-work) [inline lockfile/src/parsers/pypi.rs:21]: Would probably be more efficient to assign `line.trim()` to a temporary variable. Seems like the kind of thing that you don't necessarily want to repeat.

**Review by cd-work — CHANGES_REQUESTED** [review]

File: lockfile/src/parsers/pypi.rs (hunk 1 above)
Comment (maxrake) [reply lockfile/src/parsers/pypi.rs]: I _think_ I was able to make the suggested change. Rust is still very much unnatural to me and so I welcome any idiomatic improvements.

**Review by cd-work — APPROVED** [review]
