### PR TITLE
Fix analysis report output

### LINKED ISSUE #1116: Terminal friendly job report
The [/policy/evaluate/raw][1] endpoint is now available on staging. This should allow the CLI to create a more friendly report for job results.

Additionally, we can include more or less details with or without the `-v` option

[1]: https://api.staging.phylum.io/api/v0/swagger/index.html#/Jobs/jobs_evaluate_policy_raw

### PR DESCRIPTION
**Pull request by cd-work**
This patch uses the new raw policy endpoint to fix the output of the analysis command to be properly formatted for a terminal emulator rather than just printing the default markdown.

Closes #1116.

### CODE REVIEW

File: cli/src/api/mod.rs [hunk 1]
```diff
@@ -684,6 +697,28 @@ mod tests {
         Ok(())
     }
 
+    #[tokio::test]
+    async fn get_job_status_raw() -> Result<()> {
+        let body = todo!();
```
Comment (kylewillmon) [inline cli/src/api/mod.rs:702]: WIP?

Comment (cd-work) [reply cli/src/api/mod.rs:702]: Forgot to push the latest changes, on second.

File: cli/src/format.rs [hunk 2]
```diff
@@ -95,6 +95,65 @@ impl Format for PolicyEvaluationResponse {
...
+        // Write summary for each issue.
+        for package in &self.dependencies {
+            for rejection in package.rejections.iter().filter(|rejection| !rejection.suppressed) {
+                let severity = match rejection.source.domain.as_str() {
+                    "author" => "AUT",
+                    "engineering" => "ENG",
+                    "malicious_code" | "malicious" => "MAL",
+                    "vulnerability" => "VUL",
+                    "license" => "LIC",
+                    _ => "UNK",
```
Comment (kylewillmon) [inline cli/src/format.rs:135]: I think it would be safer to use the underlying value if we find something we're not aware of:

```suggestion
                    domain => domain,
```

I don't think that will cause lifetime issues... But I haven't compiled it...

File: cli/src/format.rs [hunk 3]
```diff
@@ -95,6 +95,65 @@ impl Format for PolicyEvaluationResponse {
...
+                };
+                let message = format!("[{severity}] {}", rejection.title);
```
Comment (kylewillmon) [inline cli/src/format.rs:137]: Hmm... You're counting on `rejection.title` to contain the name of the package...

That's definitely not guaranteed for policy-based rejections. But it seems to be true for every issue-based rejection I can find...

We probably need to discuss this with @louislang before relying on it.

File: cli/src/format.rs [hunk 4]
```diff
@@ -95,6 +95,65 @@ impl Format for PolicyEvaluationResponse {
...
+
+                let colored = match rejection.source.severity.as_str() {
+                    "low" | "info" => style(message).green(),
```
Comment (kylewillmon) [inline cli/src/format.rs:140]: Severity is weird...

If the policy rejects a `low` or `info` issue, the result is a failed job. Printing that in green seems counterintuitive.

In an ideal world, I think the policy should tell us the severity. But we're not there yet... It might be better to simply print every rejection in red since that's what we've got right now.

**Review by kylewillmon — CHANGES_REQUESTED** [review]

File: cli/src/format.rs [hunk 5]
```diff
@@ -95,6 +95,65 @@ impl Format for PolicyEvaluationResponse {
...
+            let _ = writeln!(writer, "{}", textwrap::fill(&incomplete_message, 80));
+        }
+
+        // Write summary for each issue.
+        for package in &self.dependencies {
+            for rejection in package.rejections.iter().filter(|rejection| !rejection.suppressed) {
+                let severity = match rejection.source.domain.as_str() {
+                    "author" => "AUT",
+                    "engineering" => "ENG",
+                    "malicious_code" | "malicious" => "MAL",
```
[the remark this answers is not in the document]
Comment (cd-work) [reply cli/src/format.rs]: I just copied the old code. I can force just the new version if we want to.

File: cli/src/format.rs (hunk 2 above)
Comment (cd-work) [reply cli/src/format.rs]: It will completely mess up formatting though.

File: cli/src/format.rs (hunk 3 above)
Comment (cd-work) [reply cli/src/format.rs]: I just don't want everything duplicated. The UI currently does the same. This PR's format is inspired by what the UI shows at the moment. I'm happy to change things in the future.

File: cli/src/format.rs (hunk 4 above)
Comment (cd-work) [reply cli/src/format.rs]: The UI also shows things as green even when they're technically an "issue".

I think this is just consistent with the rest of our platform.

File: cli/src/format.rs (hunk 3 above)
Comment (kylewillmon) [reply cli/src/format.rs]: I believe that will change when the UI is updated to use this endpoint. And maybe the titles will no longer contain the package names?

Comment (kylewillmon) [reply cli/src/format.rs]: I believe that will change when the UI is updated to use this endpoint. And maybe the titles will no longer contain the package names?

File: cli/src/format.rs (hunk 4 above)
Comment (louislang) [reply cli/src/format.rs]: We're working on changing this in the UI atm. Basically a transition to triaging at the package level, instead of issue level. So I'd say we should do whatever is right here, and let the rest of the platform catch up.

Comment (kylewillmon) [reply cli/src/format.rs]: After discussing with @louislang, I'm going to resolve this conversation and we can leave this as is.

There is still quite a bit of uncertainty about how this will look when the UI is updated. So matching the UI today and tweaking this code if/when the UI changes is a good strategy moving forward.

**Review by kylewillmon — APPROVED** [review]

**Review by kylewillmon — APPROVED** [review]
