### PR TITLE
Fix PNPM v5 version parsing

### LINKED ISSUE #1538: Parsing `pnpm-lock.yaml` can result in incorrect versions
# Overview
The parsing of pnpm lockfiles can sometimes result in incorrect versions.

# How To Reproduce
Steps to reproduce this behavior:
I will provide a sample file in slack.

# Expected Behavior
Correctly parse pnpm lockfiles.

# Additional Context
Entries in the lockfile like this seem to be the cause:
image

The parser returns this:
image

But the correct version is just `1.2.2`
image

### PR DESCRIPTION
**Pull request by cd-work**
This fixes an issue with the lockfile parser of PNPM v5 lockfiles which would incorrectly include metadata in the package version.

Closes #1538.

### CODE REVIEW

File: lockfile/src/javascript.rs [hunk 1]
```diff
@@ -356,16 +356,23 @@ impl PnpmLock {
         let name = key.split_once('(').map(|(name, _)| name).unwrap_or(key);
 
         // Get version separator based on PNPM version.
-        let version_separator = match version {
+        let version_separator = match pnpm_version {
```
Comment (maxrake) [inline lockfile/src/javascript.rs:359]: Not exactly related to this PR, but should the supported PNPM lockfile formats be listed in `docs/supported_lockfiles.md`? We do that for a few other lockfiles that have multiple recognized formats.

**Review by maxrake — APPROVED** [review]
One question, but approving now since the changes here address the linked issue.

File: lockfile/src/javascript.rs (hunk 1 above)
Comment (cd-work) [reply lockfile/src/javascript.rs:359]: Probably? Though we do support a wide enough version range to where I've yet to find a lockfile that we cannot parse (other than bugs like this).
