### PR TITLE
Require slashes for installing local extensions

### LINKED ISSUE #356: Extensions: Require slashes for local installs
Currently, `phylum extension add` will install extensions from a local directory.

In the future, we may have a marketplace of extensions and it would make more sense that `phylum extension add <extension-name>` adds an extension from there.

To ensure that we can distinguish between local and marketplace installations in the future, the `phylum extension add` should enforce a specific format for local installs.

After discussion, we have decided that a local install will be required to use a slash in the `phylum extension add` command. For example:

```
phylum extension add foo          # Install `foo` from marketplace
phylum extension add ./foo        # Install from local directory `foo`
phylum extension add foo/bar      # Install from local directory `foo/bar`
phylum extension add /path/to/foo # Install from local directory `/path/to/foo`
phylum extension add C:\dev\foo   # Install from local directory `C:\dev\foo`
```

## Error message
Since we do not currently support marketplace installs, any `phylum extension add` command that attempt to install from the marketplace will fail with a descriptive error message:

```
❗ Error: Attempting to install from marketplace, which is not yet supported. Did you mean `phylum extension add ./foo`
```

### PR DESCRIPTION
**Pull request by cd-work**
This reserves installation of extensions without slash, allowing us to
later use this syntax to install extensions from the marketplace without
risking users accidentally installing these remote extensions when
trying to install local ones.

Closes #356.

### CODE REVIEW

File: cli/src/commands/extensions/mod.rs [hunk 1]
```diff
@@ -73,8 +73,14 @@ pub async fn handle_extensions(matches: &ArgMatches) -> CommandResult {
 
 /// Handle the `extension add` subcommand path.
 /// Add the extension from the specified path.
-async fn handle_add_extension(path: PathBuf) -> CommandResult {
-    let extension = Extension::try_from(path)?;
+async fn handle_add_extension(path: &str) -> CommandResult {
+    // NOTE: Extension installation without slashes is reserved for the marketplace.
+    if !path.contains('/') {
```
Comment (maxrake) [inline cli/src/commands/extensions/mod.rs:78]: #356 includes an example for Windows:
```
phylum extension add C:\dev\foo   # Install from local directory `C:\dev\foo`
```
Will this work for Windows' backslash path separator? I'm still learning Rust, but my guess is that since the type of `path` is a `&str`, it means a literal backslash. Python has the notion of [`os.sep`](https://devdocs.io/python~3.7/library/os#os.sep) to represent
> The character used by the operating system to separate pathname components. This is '/' for POSIX and '\\' for Windows.

Maybe there is something similar for Rust?

**Review by maxrake — CHANGES_REQUESTED** [review]
One question and one `rustfmt` adjustment to make CI happy.

File: cli/src/commands/extensions/extension.rs [hunk 2]
```diff
@@ -114,8 +114,8 @@ impl Extension {
 
     /// Execute an extension subcommand.
     pub async fn run(&self) -> CommandResult {
-        let script_path = self.path.join(&self.manifest.entry_point);
-        let deno = DenoRuntime::new();
+        let entry_point = self.path.join(&self.manifest.entry_point);
+        let mut deno = DenoRuntime::new();
         deno.run(&entry_point.to_string_lossy()).await?;
```
Comment (mathew-horner) [inline cli/src/commands/extensions/extension.rs:119]: How did this code compile before when the variable was named `script_path` and deno needed to be mutable?

File: cli/src/commands/extensions/mod.rs (hunk 1 above)
Comment (mathew-horner) [inline cli/src/commands/extensions/mod.rs:78]: Are we supporting windows? If so, wouldn't we need to check for backslashes as well?

Comment (kylewillmon) [reply cli/src/commands/extensions/mod.rs:78]: Path types in rust support both `/` and `\` on Windows, so it's not enough to use `MAIN_SEPARATOR`.

Officially, I think what you're looking for is [`is_separator`](https://doc.rust-lang.org/std/path/fn.is_separator.html) which returns `true` for both `/` and `\` on Windows.

Practically, it's probably fine to just check for both `/` and `\`.

Comment (kylewillmon) [reply cli/src/commands/extensions/mod.rs:78]:
```suggestion
    if !path.contains('/') && !path.contains('\\') {
```

File: cli/src/commands/extensions/extension.rs (hunk 2 above)
Comment (cd-work) [reply cli/src/commands/extensions/extension.rs:119]: It didn't.

**Review by maxrake — DISMISSED** [review]

**Review by mathew-horner — DISMISSED** [review]

File: cli/src/commands/extensions/mod.rs [hunk 3]
```diff
@@ -73,8 +73,17 @@ pub async fn handle_extensions(matches: &ArgMatches) -> CommandResult {
...
```
Comment (maxrake) [inline cli/src/commands/extensions/mod.rs:78]: With the force pushes to this PR, it is not possible to see the history...but didn't this line get changed to:
`if !path.contains('/') && !path.contains('\\') {`
at one point? Did it go back?

Granted, the error message will tell the user the expected format to use, but this error message is _much_ more likely to present itself to Windows users...which may be considered unwelcoming. Perhaps a more nuanced discussion has already taken place with @kylewillmon, but he is out this week and any decisions regarding path separator support should be documented here and on the issue (#356)...which currently only says:

> After discussion, we have decided to require slashes in the argument for local installs. I have updated the title and description accordingly.

...but not which slashes or if only one type of slash will be accepted.

**Review by maxrake — COMMENTED** [review]
One remaining question to address before approval.

File: cli/src/commands/extensions/mod.rs (hunk 3 above)
Comment (cd-work) [reply cli/src/commands/extensions/mod.rs]: Yeah, good catch. This is what happens when you use the GitHub "apply suggestion" feature once every other year and then completely forget about it when you rebase the commit.
