### PR TITLE
Ignore parent directory projects for `phylum init`

### LINKED ISSUE #839: `phylum init` incorrectly warns about overwrite
When `phylum init` is run from a subdirectory of a phylum project, it incorrectly warns that it is going to overwrite an existing project config.

# How To Reproduce
From a directory `~/tmp/foo`:

```
❯ find ..
..
../.phylum_project
../foo

❯ phylum init
⚠️  Workspace is already linked to a Phylum project
Overwrite existing project configuration? yes

Project Name: foo
Use a project group? no
✅ Successfully created project "foo"

Project lockfile path: package-lock.json

❯ find ..
..
../.phylum_project
../foo
../foo/.phylum_project
```

# Expected Behavior
We should remove the warning in this case.

### PR DESCRIPTION
**Pull request by cd-work**
Previously, `phylum init` would query if the project should be overwritten when a parent project contained a project file already.

Since we do not actually overwrite any project files outside of the current directory, and since having nested Phylum projects is perfectly valid, a warning is now only emitted when there's already a Phylum project file in the current directory.

Closes #839.

### CODE REVIEW

File: cli/src/config.rs [hunk 1]
```diff
@@ -170,27 +170,27 @@ pub fn read_configuration(path: &Path) -> Result<Config> {
...
-    let mut attempts = 0;
-    const MAX_DEPTH: u8 = 32;
-
-    loop {
-        let search_path = path.join(PROJ_CONF_FILE);
-        if search_path.is_file() {
-            return Some(search_path);
+pub fn find_project_conf(
+    starting_directory: impl AsRef<Path>,
+    recurse_upwards: bool,
```
Comment (cd-work) [inline cli/src/config.rs:175]: While we could have checked if the `find_project_conf` returned Path's parent is equal to the current directory, that would have meant traversing the entire directory tree just to discard it. So I've decided to go for the simpler solution and just added an option to skip the traversal.

File: cli/src/config.rs [hunk 2]
```diff
@@ -170,27 +170,27 @@ pub fn read_configuration(path: &Path) -> Result<Config> {
...
+) -> Option<PathBuf> {
+    let max_depth = if recurse_upwards { 32 } else { 1 };
+    let mut path = starting_directory.as_ref();
+
+    for _ in 0..max_depth {
```
Comment (cd-work) [inline cli/src/config.rs:180]: I've decided to just rewrite the loop here completely. It's shorter and using `parent` should be easier to understand and at the same time aborts early instead of pointlessly looping when we're already at the root.

**Review by andreaphylum — APPROVED** [review]

**Comment by cd-work** [comment]
Don't merge this, I think I want to actually add the project file's root directory to our project conf struct.

**Comment by cd-work** [comment]
Will rewrite this once https://github.com/phylum-dev/cli/pull/845 is merged.

**Comment by cd-work** [comment]
I decided to keep things pretty much identical since reading the `root` field on the config still isn't really easier than not recursing. We'd have to do expensive recursive lookup and parse the entire config just to at the end still have to compare paths that we might have to canonicalize first. So not really worth it, much easier to just skip the directory traversal and see if we find something at all.

**Review by andreaphylum — APPROVED** [review]

**Review by andreaphylum — DISMISSED** [review]

File: cli/src/config.rs [hunk 3]
```diff
@@ -197,27 +197,27 @@ pub fn read_configuration(path: &Path) -> Result<Config> {
...
 
-        if attempts > MAX_DEPTH {
-            return None;
-        }
-        path.push("..");
-        attempts += 1;
+        path = path.parent()?;
     }
+
+    None
```
[the remark this answers is not in the document]
Comment (cd-work) [reply cli/src/config.rs:216]: Definitely a good idea, yeah.

**Review by kylewillmon — APPROVED** [review]
