### PR TITLE
Move token tests to integration

### LINKED ISSUE #590: Unit test race condition with environment variables
Multiple unit tests are using the same environment variable, which is causing a race condition and sporadic failures like this:

```
---- config::tests::test_pass_api_key_through_env stdout ----
⚠️  Ignoring empty PHYLUM_API_KEY
thread 'config::tests::test_pass_api_key_through_env' panicked at 'assertion failed: `(left == right)`
  left: `Some(RefreshToken("FAKE TOKEN"))`,
 right: `Some(RefreshToken("ENV VARIABLE TOKEN"))`', cli/src/config.rs:247:9
```

There are multiple ways to fix this, but here is a suggestion from @cd-work:

> Have you considered moving this to integration testing maybe, where things are executed as separate processes? We can still validate tokens using the `phylum token` subcommand.

_Originally posted by @cd-work in https://github.com/phylum-dev/cli/pull/589#pullrequestreview-1060907675_

### PR DESCRIPTION
**Pull request by cd-work**
To allow for easily creating new integration test modules, the
integration test setup has been reworked to work as a single big crate.

The config file is now passed to our CLI builder as an `Option<Config>`,
allowing us to override the configuration file with a different value.

The `run` method was also removed from `TestCli` since it just
unnecessarily restricted the capabilities of the returned type. Instead
the full `Command` is returned so consumers can modify args, env, etc
themselves.

Closes #590.

### CODE REVIEW

File: cli/tests/common.rs [hunk 1]
```diff
@@ -95,15 +97,15 @@ impl TestCli {
...
+        self.cmd().args(&["extension", "install", "-y", &path.to_string_lossy()]).assert()
     }
 
     #[cfg(feature = "extensions")]
     pub fn extension<'a>(&'a self, code: &'a str) -> TestExtensionBuilder<'a> {
         TestExtensionBuilder::new(self, code)
     }
 
-    pub fn run<S: AsRef<str> + AsRef<OsStr>>(&self, args: &[S]) -> Assert {
+    pub fn cmd(&self) -> Command {
```
Comment (andreaphylum) [inline cli/tests/common.rs:108]: I'm ok with this change but I'd _also_ add a `run` (or more appropriately named) shorthand method to avoid repeating `cmd().args(&[...]).assert()` everywhere.

File: cli/tests/end_to_end/extension.rs [hunk 2]
```diff
@@ -5,7 +5,7 @@ use crate::common::{create_lockfile, create_project, TestCli};
 /// Test Phylum API functions.
 #[tokio::test]
 pub async fn get_user_info() {
-    let test_cli = TestCli::builder().with_config(true).build();
+    let test_cli = TestCli::builder().with_config(None).build();
```
Comment (andreaphylum) [inline cli/tests/end_to_end/extension.rs:8]: I would rather have something like `Default::default()` here, as `None` intuitively means "with no config", while the semantics of this call are "with a config, but don't specify which".

If we don't need to create a config, we can just skip the `.with_config()` invocation altogether.

**Review by andreaphylum — CHANGES_REQUESTED** [review]

File: cli/tests/end_to_end/extension.rs (hunk 2 above)
Comment (cd-work) [reply cli/tests/end_to_end/extension.rs:8]: > If we don't need to create a config, we can just skip the .with_config() invocation altogether.

Yeah that's exactly why I chose `None` as parameter. These are tests and brevity is somewhat important. So I think having to specify the config every time would be annoying, especially because `Config::default` will not work.

Comment (andreaphylum) [reply cli/tests/end_to_end/extension.rs:8]: How about adding `.with_default_config()` or similar name (maybe shorter)? It's an extra one-liner method but it would be used in most places.

Comment (cd-work) [reply cli/tests/end_to_end/extension.rs:8]: It wouldn't be the default config though? I'm not sure tbh, I don't like having two different methods like this.

**Review by andreaphylum — APPROVED** [review]

File: cli/tests/end_to_end/extension.rs (hunk 2 above)
Comment (andreaphylum) [reply cli/tests/end_to_end/extension.rs:8]: I'd say this is not a dealbreaker anyway. We can keep the current solution.
