### PR TITLE
Handle `-h`, `--help` and `help` as first argument of `extension run`

### LINKED ISSUE #597: `phylum extension run` doesn't allow double-hyphen parameters
When running an installed extension using parameters like `phylum npm install --save typescript` it works without any problems, however when doing the same using `phylum extension run ./npm install --save typescryt` clap throws an error since it cannot recognize the `--save` flag.

To make sure people can fully test their extensions with just `phylum extension run` and provide a consistent user experience, we should support double-hyphen flags in both.

### LINKED ISSUE #605: Help output for `phylum extension run` causes error
# Overview

The `phylum extension run --help` command results in an error and no help message is displayed.

# How To Reproduce

Steps to reproduce this behavior:
1. With a CLI that includes extensions, run `phylum extension run --help`
2. See error

# Expected Behavior

Running `--help` on any CLI command results in a useful help message

# Additional Context

Screenshot:

image

### PR DESCRIPTION
**Pull request by andreaphylum**
Closes #605.

Adds a hard-coded handling of the `-h` and `--help` flags and `help` subcommand when those are supplied as first parameter to `phylum extension run`.

### CODE REVIEW

File: cli/src/bin/phylum.rs [hunk 1]
```diff
@@ -147,7 +147,7 @@ async fn handle_commands() -> CommandResult {
         #[cfg(feature = "selfmanage")]
         "uninstall" => uninstall::handle_uninstall(sub_matches),
 
-        "extension" => extensions::handle_extensions(Box::pin(api), sub_matches).await,
+        "extension" => extensions::handle_extensions(app_helper, Box::pin(api), sub_matches).await,
```
Comment (cd-work) [inline cli/src/bin/phylum.rs:150]: Not sure but we might want to keep API as first parameter just for consistency with everything else?

**Review by cd-work — CHANGES_REQUESTED** [review]
Very clean and simple, nice.

File: cli/src/bin/phylum.rs (hunk 1 above)
Comment (andreaphylum) [reply cli/src/bin/phylum.rs]: Makes sense to me -- I put it as last argument to also preserve consistency with other methods having `sub_matches` as second argument.

**Review by cd-work — APPROVED** [review]
