### PR TITLE
Fix generation error for invalid lockifests

### LINKED ISSUE #1295: Lockifest manifests generate errors when `--no-generation` set
# Overview

Attempting to parse a Python [lockifest](https://docs.phylum.io/docs/lockfile_generation#lockifests) with the `--no-generation` option results in an unhandled parsing error when the lockifest is a manifest.

## How To Reproduce

Steps to reproduce this behavior:

<details><summary>Details (click to expand)</summary>
<p>

```
# Show the current released version
❯ phylum --version
phylum v5.8.1

# Create a basic Python lockifest manifest
❯ cat requirements.txt
pyyaml

# Show the current released version works as expected
❯ phylum parse --lockfile-type pip ./requirements.txt
Generating lockfile for manifest "requirements.txt" using Pip…
[
  {
    "name": "PyYAML",
    "version": "6.0.1",
    "type": "pypi",
    "lockfile": "requirements.txt"
  }
]

# Update to the latest release candidate
❯ phylum update --prerelease

    phylum-cli installer

    OK Copied completions to /Users/maxrake/.local/share/phylum/completions
Installing extension bundle...
✅ Extension bundle already installed, nothing to do
Installing extension cargo...
✅ Extension cargo already installed, nothing to do
Installing extension npm...
✅ Extension npm already installed, nothing to do
Installing extension pip...
✅ Extension pip already installed, nothing to do
Installing extension poetry...
✅ Extension poetry already installed, nothing to do
Installing extension yarn...
✅ Extension yarn already installed, nothing to do
    OK Installed default extensions
    OK Completions are enabled for bash.
    OK Completions are enabled for zsh.
    OK Successfully installed phylum.

    Source your /Users/maxrake/.zshrc file, add /Users/maxrake/.local/bin to your $PATH variable, or
    log in to a new terminal in order to make `phylum` available.

✅ Successfully updated to v5.9.0-rc1!

# Show the RC version
❯ phylum --version
phylum v5.9.0-rc1

# Show the RC version works when `--no-generation` is NOT specified
❯ phylum parse --lockfile-type pip ./requirements.txt
Generating lockfile for manifest "requirements.txt" using Pip…
[
  {
    "name": "PyYAML",
    "version": "6.0.1",
    "type": "pypi",
    "lockfile": "requirements.txt"
  }
]

# Show the RC version fails when `--no-generation` IS specified
❯ phylum parse --lockfile-type pip --no-generation ./requirements.txt
❗ Error: could not parse lockfile: ./requirements.txt

Caused by:
    0: Failed to parse lockfile
    1: Failed to parse requirements file
    2: 0: at line 1, in Tag:
       pyyaml
             ^

# Show the RC version works when `--skip-sandbox` is specified
❌ 1 ❯ phylum parse --lockfile-type pip --skip-sandbox ./requirements.txt
Generating lockfile for manifest "requirements.txt" using Pip…
[
  {
    "name": "PyYAML",
    "version": "6.0.1",
    "type": "pypi",
    "lockfile": "requirements.txt"
  }
]

# Show the RC version fails when `--no-generation` IS specified along with `--skip-sandbox`
❯ phylum parse --lockfile-type pip --skip-sandbox --no-generation ./requirements.txt
❗ Error: could not parse lockfile: ./requirements.txt

Caused by:
    0: Failed to parse lockfile
    1: Failed to parse requirements file
    2: 0: at line 1, in Tag:
       pyyaml
             ^
```

</p>
</details> 

## Expected Behavior

Python lockifests are recognized as manifests when they are manifests and parsing is NOT attempted when `--no-generation` is supplied as an option for the `parse`/`analyze` commands. Instead, the error code 20 should be returned, along with the same message as when other manifests are attempted to be parsed with the `--no-generation` option:

```
❗ Could not parse lockfile: Parsing "./requirements.txt" requires lockfile generation, but it was disabled through the CLI
```

Python lockifests are recognized as lockfiles when they are lockfiles and parsing is attempted when `--no-generation` is supplied as an option for the `parse`/`analyze` commands.

## Additional Context

N/A

### PR DESCRIPTION
**Pull request by cd-work**
This changes the error output for lockifests which cannot be parsed as lockfiles when manifest generation is disabled with `--no-generation`. Instead of printing the parsing error of the lockfile, we now print an error that manifest generation is required.

Closes #1295.

### CODE REVIEW

File: cli/src/commands/parse.rs [hunk 1]
```diff
@@ -135,11 +135,13 @@ pub fn parse_lockfile(
     }
 
     // Abort if generation is disabled or path is neither lockfile nor manifest.
-    if !generate_lockfiles || !parser.is_path_manifest(&path) {
+    let maybe_manifest = parser.is_path_manifest(&path);
+    if !generate_lockfiles || !maybe_manifest {
```
Comment (mathew-horner) [inline cli/src/commands/parse.rs:139]: nit/imo: I think this is slightly easier to read if you apply DML.
```suggestion
    if !(generate_lockfiles && maybe_manifest) {
```

**Review by mathew-horner — APPROVED** [review]

**Review by maxrake — APPROVED** [review]
Tested locally and it works as expected. LGTM.

**Review by mathew-horner — APPROVED** [review]
