### PR TITLE
Filter non-PyPi dependencies from poetry lockfile

### LINKED ISSUE #269: Python Poetry parser does not account for package source
# Overview
The current implementation of the Python `poetry.lock` file parser does not account for `package.source` sub-tables. That is the mechanism the [`poetry-core` library uses for specifying dependency types](https://github.com/python-poetry/poetry-core/blob/master/src/poetry/core/packages/types.py), when the type is not a "basic" dependency that can be fully specified in the `package` table entry alone. Such types include: `DirectoryDependency`, `FileDependency`, `URLDependency`, and `VCSDependency`. Therefore, when the `poetry.lock` file contains a dependency with a `package.source` sub-table, it gets treated as a "basic" `Dependency` type instead. This can result in analyzing the wrong dependency, when the same package/version pair exists in PyPI.

# How To Reproduce
Steps to reproduce this behavior:
1. View the [phylum-dev/vulnerabilities-admin private repo `poetry.lock` file](https://github.com/phylum-dev/vulnerabilities-admin/blob/development/poetry.lock), specifically the [entry for the `common` package](https://github.com/phylum-dev/vulnerabilities-admin/blob/development/poetry.lock#L265-L278)
2. Notice that the `common` package there is specifying a VCSDependency of a _private_ git repo, [phylum-dev/common](https://github.com/phylum-dev/common), which indeed has a Python package defined in the [setup.py](https://github.com/phylum-dev/common/blob/development/setup.py) file there of `common v0.1.0`
3. Perform a `phylum analyze` on the `poetry.lock` file
4. View the results in the Web UI to see that the package was attempted to be downloaded...but for the [`common==0.1` package that exists in the _public_ PyPI](https://pypi.org/project/common/0.1/#files)
5. This is a form of [dependency confusion](https://dhiyaneshgeek.github.io/web/security/2021/09/04/dependency-confusion/), but within the CLI parser; the package installer (Poetry) will still know how to parse and install the correct package

# Expected Behavior
The packages in the `poetry.lock` file that have a `package.source` sub-table...which specifies something other than a basic dependency available in the PyPI public package registry...will be filtered out by CLI parser and not included in the list of packages to analyze.

# Additional Context
* The [poetry `Locker` class](https://github.com/python-poetry/poetry/blob/fb13b3a676f476177f7937ffa480ee5cff9a90a5/src/poetry/packages/locker.py#L45-L49) is really the only "documentation" that exists for the `poetry.lock` file format
  * This link is for the current version of that lockfile, v1.1
* The Poetry project repo has some test files and fixtures that might help
  * [`python-poetry/poetry/tests/packages/test_locker.py`](https://github.com/python-poetry/poetry/blob/da9680b0faee435a9d4fb52ac4b11b7a18c48069/tests/packages/test_locker.py)
  * [`python-poetry/poetry/tests/fixtures`](https://github.com/python-poetry/poetry/tree/da9680b0faee435a9d4fb52ac4b11b7a18c48069/tests/fixtures)
* The build backend for Poetry is broken out into it's own repo, [`poetry-core`](https://github.com/python-poetry/poetry-core)
  * The package types are defined there: [`python-poetry/poetry-core/src/poetry/core/packages`](https://github.com/python-poetry/poetry-core/tree/master/src/poetry/core/packages) and [`python-poetry/poetry-core/src/poetry/core/packages/types.py`](https://github.com/python-poetry/poetry-core/blob/master/src/poetry/core/packages/types.py) as a good starting point
* The CLI parser for Python `requirements.txt` files [appears to have logic to further filter out dependencies](https://github.com/phylum-dev/cli/blob/8a6ecf5344301115fa1a8b69f2d3b1f1b72be461/cli/src/lockfiles/python.rs#L27) by using the [`parsers::pypi::parse` module](https://github.com/phylum-dev/cli/blob/8a6ecf5344301115fa1a8b69f2d3b1f1b72be461/cli/src/lockfiles/parsers.rs#L157)
  * Perhaps something similar can be done for `poetry.lock` files

### PR DESCRIPTION
**Pull request by cd-work**
This patch filters the poetry lockfile to ensure only packages which are
present in PyPi are submitted, to avoid potential dependency confusion.

To ensure the poetry lockfile parser's robustness, a new test lockfile
has been created which makes use of every possible dependency type other
than `legacy`.

Closes #269.

### CODE REVIEW

**Comment by maxrake** [comment]
> I think we might want to capture maybe VCS dependencies at a minimum. The [request manager](https://github.com/phylum-dev/request-manager/blob/8f4d1bb04dc20066d2f9bdf5be939a03295857d8/src/models.py#L480) will allow a URL as the version.

If VCS support is added, will the CLI or the request manager (or both?) be responsible for knowing if the VCS is public/accessible or private/inaccessible? The [phylum-dev/vulnerabilities-admin private repo `poetry.lock` file](https://github.com/phylum-dev/vulnerabilities-admin/blob/development/poetry.lock), specifically the [entry for the `common` package](https://github.com/phylum-dev/vulnerabilities-admin/blob/development/poetry.lock#L265-L278) is an example of a private GitHub repository that I would guess request manager is unable to access.

**Comment by ejortega** [comment]
> > I think we might want to capture maybe VCS dependencies at a minimum. The [request manager](https://github.com/phylum-dev/request-manager/blob/8f4d1bb04dc20066d2f9bdf5be939a03295857d8/src/models.py#L480) will allow a URL as the version.
> 
> If VCS support is added, will the CLI or the request manager (or both?) be responsible for knowing if the VCS is public/accessible or private/inaccessible? The [phylum-dev/vulnerabilities-admin private repo `poetry.lock` file](https://github.com/phylum-dev/vulnerabilities-admin/blob/development/poetry.lock), specifically the [entry for the `common` package](https://github.com/phylum-dev/vulnerabilities-admin/blob/development/poetry.lock#L265-L278) is an example of a private GitHub repository that I would guess request manager is unable to access.

This could be older info and maybe has changed. @louislang or @eeclfrei asked me to modify some of the scoring issues at one point due to VCS entries included in NPM lockfiles. I believe the handling of private/public would be done by another service and not the CLI.

**Review by maxrake — APPROVED** [review]
The changes were confirmed to work with the `vulnerabilities-admin` poetry.lock file that initiated this issue. So...LGTM.

As for the VCS support...either adding that here or in a new issue/PR is acceptable.

**Comment by ejortega** [comment]
@cd-work [python requirements parser ](https://github.com/phylum-dev/cli/blob/18a0a03752b7fc24cd4961ba2314e200859fc35f/cli/src/lockfiles/parsers/pypi.rs#L37).

File: cli/src/lockfiles/python.rs [hunk 1]
```diff
@@ -130,18 +136,35 @@ struct PoetryLock {
...
+    source: Option<PackageSource>,
 }
 
 impl From<Package> for PackageDescriptor {
     fn from(package: Package) -> Self {
+        let version = package
+            .source
+            .and_then(|source| {
+                let reference = source.resolved_reference.as_ref();
+                reference.map(|reference| format!("{}#{}", source.url, reference))
```
Comment (maxrake) [inline cli/src/lockfiles/python.rs:148]: There is still some uncertainty...but the current thought is that the format for the version on this line is not quite what the `request-manager` expects. Feeding the [`poetry.lock` file from `vulnerabilities-admin`](https://github.com/phylum-dev/vulnerabilities-admin/blob/poetry_month/poetry.lock) results in the following error...which appears to be due to failing to match any of the version regex's in request-manager...specifically [this one](https://github.com/phylum-dev/request-manager/blob/bb1d4bfecabb63a8aba79ed86df91af31dd1fb82/src/models.py#L480).

```sh
❯ ./phylum analyze -l poetry_type_test_4 -F poetry.lock
[2022-04-19T17:16:34Z ERROR phylum] Execution failed: Improperly formatted creation request
❗ Error: Execution failed caused by: Improperly formatted creation request
```

My regex foo is limited, but perhaps @ejortega can assist.

**Review by maxrake — CHANGES_REQUESTED** [review]
Changes appear good...and updates to the unit tests do show them to pass...but a functional test, using the production system, shows a failure. See the comment for more detail.

File: cli/src/lockfiles/python.rs (hunk 1 above)
Comment (cd-work) [reply cli/src/lockfiles/python.rs:148]: The regex definitely doesn't match `https` URLs. I'm not sure any format that is supported in `poetry.lock` is also supported by this regex.

Comment (ejortega) [reply cli/src/lockfiles/python.rs:148]: I'm testing out some changes with request-manager and api

**Comment by maxrake** [comment]
A bug ticket was created in the `request-manager` repo to track the issue blocking this PR:
* [Model doesn't handle certain VCS urls](https://github.com/phylum-dev/request-manager/issues/80)

File: cli/src/lockfiles/python.rs (hunk 1 above)
Comment (cd-work) [reply cli/src/lockfiles/python.rs:148]: The URLs work correctly now.

**Review by maxrake — APPROVED** [review]
Confirmed the changes (on staging environment) do work as intended. There is a different issue I noticed while doing that testing...but it is not related to this PR or even the CLI. So...LGTM.

File: cli/src/lockfiles/python.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (maxrake) [reply cli/src/lockfiles/python.rs:148]: looks good on staging now.
